package dev.sequel.app.data.remote.supabase.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase row for the `watched_movies` table.
 * Matches the PostgreSQL schema on Supabase.
 */
@Serializable
data class SupabaseWatchedMovieDto(
    @SerialName("id")
    val id: String? = null, // UUID, auto-generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("tmdb_movie_id")
    val tmdbMovieId: Int,

    @SerialName("title")
    val title: String = "Unknown Title",

    @SerialName("poster_path")
    val posterPath: String? = null,

    @SerialName("watched_at")
    val watchedAt: Long,

    @SerialName("created_at")
    val createdAt: String? = null // ISO timestamp, auto-generated
)
