package dev.sequel.app.data.remote.supabase.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase row for the `watched_episodes` table.
 * Matches the PostgreSQL schema on Supabase.
 */
@Serializable
data class SupabaseWatchedEpisodeDto(
    @SerialName("id")
    val id: String? = null, // UUID, auto-generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("tmdb_show_id")
    val tmdbShowId: Int,

    @SerialName("tmdb_episode_id")
    val tmdbEpisodeId: Int,

    @SerialName("season_number")
    val seasonNumber: Int,

    @SerialName("episode_number")
    val episodeNumber: Int,

    @SerialName("watched_at")
    val watchedAt: Long,

    @SerialName("created_at")
    val createdAt: String? = null // ISO timestamp, auto-generated
)
