package dev.sequel.app.data.remote.supabase.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase row for the `reviews` table.
 */
@Serializable
data class SupabaseReviewDto(
    @SerialName("id")
    val id: String? = null, // UUID, auto-generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("media_id")
    val mediaId: Int,

    @SerialName("season_num")
    val seasonNum: Int? = null,

    @SerialName("episode_num")
    val episodeNum: Int? = null,

    @SerialName("review_text")
    val reviewText: String? = null,

    @SerialName("vibe_emoji")
    val vibeEmoji: String? = null,

    @SerialName("is_spoiler")
    val isSpoiler: Boolean = false,

    @SerialName("created_at")
    val createdAt: String? = null // ISO timestamp
)
