package dev.sequel.app.data.remote.supabase.dto

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase row for the `reviews` table.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class SupabaseReviewDto(
    @SerialName("id")
    val id: String? = null, // UUID, auto-generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("media_id")
    val mediaId: Int,

    @SerialName("media_type")
    val mediaType: String? = null,

    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    @SerialName("season_num")
    val seasonNum: Int? = null,

    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    @SerialName("episode_num")
    val episodeNum: Int? = null,

    @SerialName("review_text")
    val reviewText: String? = null,

    @SerialName("rating")
    val rating: Int? = null,

    @SerialName("is_spoiler")
    val isSpoiler: Boolean = false,

    @SerialName("created_at")
    val createdAt: String? = null, // ISO timestamp
    
    @SerialName("updated_at")
    val updatedAt: Long? = null
)
