package dev.sequel.app.data.remote.supabase.dto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Supabase row for the `reviews` table.
 */
@Serializable
data class SupabaseReviewDto(
    @SerialName("id")
    val id: String? = null, // UUID, auto-generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("tmdb_show_id")
    val tmdbShowId: Int,

    @SerialName("rating")
    val rating: Int,

    @SerialName("review_text")
    val reviewText: String? = null,

    @SerialName("created_at")
    val createdAt: String? = null, // ISO timestamp

    @SerialName("updated_at")
    val updatedAt: String? = null
)
